# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Name',
            field=models.TextField(default='my name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='my bio'),
        ),
    ]
